import Mongo from "../../Mongo";

export default class Fields extends Mongo {
	ACTION_TYPE = "action_type";
	RECEIVED = "received";
	PENDING = "pending";
	_ID = "_id";
	PARENT = "parent";
	SERVICES = "services";
	EVENT = "event";
	EVENTS = "events";
	MODEL = "model";
	MIDDLEWARE = "middleware";
	MODELS = "models";
	_DB = "_db";
	CREATED_AT = "created_at";
	UPDATED_AT = "updated_at";
	DELETED_AT = "deleted_at";
	ACTION = "action";
	IS_COMPLETED = "is_completed";
	NOTE = "note";
	SCORE = "score";
	TYPE = "type";
	APPROVED = "approved";
	DECLINED = "declined";
	ESCALATED = "escalated";
	MAIL_ADDRESS = "mail_address";
	IS_DELETED = "is_deleted";
	OTHER = "other";
	YES = "yes";
	NO = "no";
	REQUIRED = "required";
	ARRAY = "array";
	UNDO = "undo";
	REDO = "redo";
	GET = "get";
	POST = "post";
	DELETE = "delete";
	_DELETE = "_delete";
	UPDATE = "update";
	X_DELETE_ALL = "x-delete-all";
	INSERT = "insert";
	FIND_ONE_AND_UPDATE = "findOneAndUpdate";
	X_TOTAL_COUNT = "x-total-count";
	NAME = "name";
	EMAIL = "email";
	PHONE_NUMBER = "phone_number";
	ADDRESS = "address";
	CLASS = "class";
	CONTENT = "content";
	HTML = "html";
	QUESTION = "question";
	USER_ID = "user_id";
	ASSETS = "assets";
	TEMPLATE = "template";
	TEMPLATES = "templates";

	EXPANDS = {};
}

