import Message from "./Message";

export default class Code extends Message {
	OK_CODE = 200;
	CREATED_CODE = 201;
	ACCEPTED_CODE = 202;
	NON_AUTHORITATIVE_INFORMATION_CODE = 203;
	NO_CONTENT_CODE = 204;
	BAD_REQUEST_CODE = 400;
	CONSENT_PENDING_CODE = 400;
	INVALID_TYPE_CODE = 400;
	FIELD_DUPLICATE_CODE = 400;
	UNAUTHORIZED_CODE = 401;
	TOKEN_EXPIRED_CODE = 401;
	FORBIDDEN_CODE = 403;
	NOT_FOUND_CODE = 404;
	RESOURCE_NOT_FOUND_CODE = 404;
	METHOD_NOT_ALLOWED_CODE = 405;
	NOT_ACCEPTABLE_CODE = 406;
	REQUEST_TIMEOUT_CODE = 408;
	UNSUPPORTED_MEDIA_TYPE_CODE = 415;
	TOO_MANY_REQUEST_CODE = 429;
	FIELD_REQUIRED_CODE = 400;
	FIELD_INVALID_CODE = 400;
	FAILED_CODE = 400;
	FAILURE_CODE = 404;
	GENERIC_CODE = 500;

	SUCCESS_CODE: any = {
		GET: this.OK_CODE,
		POST: this.CREATED_CODE,
		DELETE: this.OK_CODE,
		PATCH: this.OK_CODE,
		PUT: this.OK_CODE,
	};
}
