import Code from "./Code";

export default class Status extends Code {
	OK_STATUS = "SUCCESS";
	CREATED_STATUS = "CREATED";
	GENERIC_STATUS = "GENERIC";
	ACCEPTED_STATUS = "ACCEPTED";
	NOT_FOUND_STATUS = "NOT_FOUND";
	RESOURCE_NOT_FOUND_STATUS = "RESOURCE_NOT_FOUND";
	FORBIDDEN_STATUS = "FORBIDDEN";
	NO_CONTENT_STATUS = "NO_CONTENT";
	BAD_REQUEST_STATUS = "FAILED";
	UNAUTHORIZED_STATUS = "UNAUTHORIZED";
	TOKEN_EXPIRED_STATUS = "TOKEN_EXPIRED";
	FIELD_INVALID_STATUS = "FIELD_INVALID";
	FAILURE_STATUS = "FAILURE";
	INVALID_TYPE_STATUS = "INVALID_TYPE";
	CONSENT_PENDING_STATUS = "CONSENT_PENDING";
	UNKNOWN_ERROR_STATUS = "SOMETHING_WENT_WRONG";
	FIELD_REQUIRED_STATUS = "FIELD_REQUIRED";
	FIELD_DUPLICATE_STATUS = "FIELD_DUPLICATE";
	NOT_ACCEPTABLE_STATUS = "NOT_ACCEPTABLE";
	REQUEST_TIMEOUT_STATUS = "REQUEST_TIMEOUT";
	TOO_MANY_REQUEST_STATUS = "LIMIT_REACHED";
	METHOD_NOT_ALLOWED_STATUS = "METHOD_NOT_ALLOWED";
	UNSUPPORTED_MEDIA_TYPE_STATUS = "UNSUPPORTED_MEDIA_TYPE";
	NON_AUTHORITATIVE_INFORMATION_STATUS = "NON_AUTHORITATIVE_INFORMATION";

	SUCCESS_STATUS: any = {
		GET: this.OK_STATUS,
		POST: this.CREATED_STATUS,
		DELETE: this.OK_STATUS,
		PATCH: this.OK_STATUS,
		PUT: this.OK_STATUS,
	};

	TYPES: any = {
		query: "query",
		headers: "headers",
		body: "body",
		form_data: "form-data",
	};
}
